/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (server-fsm.h)
 *
 *  It has been AutoGen-ed
 *  From the definitions    ./server.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2016 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 *  This file enumerates the states and transition events for a FSM.
 *
 *  te_smtp_server_state
 *      The available states.  FSS_INIT is always defined to be zero
 *      and FSS_INVALID and FSS_DONE are always made the last entries.
 *
 *  te_smtp_server_event
 *      The transition events.  These enumerate the event values used
 *      to select the next state from the current state.
 *      SMTP_SERVER_EV_INVALID is always defined at the end.
 */
#ifndef AUTOFSM_SERVER_FSM_H_GUARD
#define AUTOFSM_SERVER_FSM_H_GUARD 1
/**
 *  Finite State machine States
 *
 *  Count of non-terminal states.  The generated states INVALID and DONE
 *  are terminal, but INIT is not  :-).
 */
#define SMTP_SERVER_STATE_CT  8
typedef enum {
    SMTP_SERVER_ST_INIT,             SMTP_SERVER_ST_READY,
    SMTP_SERVER_ST_NEED_SENDER,      SMTP_SERVER_ST_NEED_RECIPIENT,
    SMTP_SERVER_ST_NEED_DATA,        SMTP_SERVER_ST_WAITING_FOR_DATA,
    SMTP_SERVER_ST_SAVING_MAIL,      SMTP_SERVER_ST_CLOSED,
    SMTP_SERVER_ST_INVALID,          SMTP_SERVER_ST_DONE
} te_smtp_server_state;

/**
 *  Finite State machine transition Events.
 *
 *  Count of the valid transition events
 */
#define SMTP_SERVER_EVENT_CT 14
typedef enum {
    SMTP_SERVER_EV_CMND_NOOP,     SMTP_SERVER_EV_CMND_HELO,
    SMTP_SERVER_EV_CMND_EHLO,     SMTP_SERVER_EV_CMND_MAIL,
    SMTP_SERVER_EV_CMND_RCPT,     SMTP_SERVER_EV_CMND_VRFY,
    SMTP_SERVER_EV_CMND_DATA,     SMTP_SERVER_EV_CMND_RSET,
    SMTP_SERVER_EV_CMND_QUIT,     SMTP_SERVER_EV_MAIL_END,
    SMTP_SERVER_EV_MAIL_DATA,     SMTP_SERVER_EV_MAIL_SAVED,
    SMTP_SERVER_EV_CONN_ACCEPTED, SMTP_SERVER_EV_CONN_LOST,
    SMTP_SERVER_EV_INVALID
} te_smtp_server_event;

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  SMTP_SERVER_ST_DONE or SMTP_SERVER_ST_INVALID, it resets to
 *  SMTP_SERVER_ST_INIT and returns SMTP_SERVER_ST_INIT.
 */
extern te_smtp_server_state
smtp_server_step(
    te_smtp_server_state smtp_server_state,
    te_smtp_server_event trans_evt,
    int client_socket_fd,
    char*** matchdata,
    int matchdatalen,
    int** matchdatasizes );

#endif /* AUTOFSM_SERVER_FSM_H_GUARD */
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of server-fsm.h */
