/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (server-fsm.c)
 *
 *  It has been AutoGen-ed
 *  From the definitions    server.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2018 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define DEFINE_FSM
#include "server-fsm.h"
#include <stdio.h>

#include <stdlib.h>
#include "../state_handlers.h"
#include "../client_info.h"

/*
 *  Do not make changes to this file, except between the START/END
 *  comments, or it will be removed the next time it is generated.
 */
/* START === USER HEADERS === DO NOT CHANGE THIS COMMENT */
/* END   === USER HEADERS === DO NOT CHANGE THIS COMMENT */

#ifndef NULL
#  define NULL 0
#endif

/**
 *  Enumeration of the valid transition types
 *  Some transition types may be common to several transitions.
 */
typedef enum {
    SMTP_SERVER_TR_ACCEPTED,
    SMTP_SERVER_TR_CMND_CLOSE,
    SMTP_SERVER_TR_CMND_DATA,
    SMTP_SERVER_TR_CMND_EHLO,
    SMTP_SERVER_TR_CMND_HELO,
    SMTP_SERVER_TR_CMND_MAIL,
    SMTP_SERVER_TR_CMND_NOOP,
    SMTP_SERVER_TR_CMND_RCPT,
    SMTP_SERVER_TR_CMND_RSET,
    SMTP_SERVER_TR_CMND_VRFY,
    SMTP_SERVER_TR_INVALID,
    SMTP_SERVER_TR_MAIL_DATA,
    SMTP_SERVER_TR_MAIL_END
} te_smtp_server_trans;
#define SMTP_SERVER_TRANSITION_CT  13

/**
 *  State transition handling map.  Map the state enumeration and the event
 *  enumeration to the new state and the transition enumeration code (in that
 *  order).  It is indexed by first the current state and then the event code.
 */
typedef struct smtp_server_transition t_smtp_server_transition;
struct smtp_server_transition {
    te_smtp_server_state  next_state;
    te_smtp_server_trans  transition;
};
static const t_smtp_server_transition
smtp_server_trans_table[ SMTP_SERVER_STATE_CT ][ SMTP_SERVER_EVENT_CT ] = {

  /* STATE 0:  SMTP_SERVER_ST_INIT */
  { { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_NOOP */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_HELO */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_EHLO */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_MAIL */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_RCPT */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_VRFY */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_DATA */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_RSET */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_QUIT */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  MAIL_END */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  MAIL_DATA */
    { SMTP_SERVER_ST_READY, SMTP_SERVER_TR_ACCEPTED }, /* EVT:  CONN_ACCEPTED */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID } /* EVT:  CONN_LOST */
  },


  /* STATE 1:  SMTP_SERVER_ST_READY */
  { { SMTP_SERVER_ST_READY, SMTP_SERVER_TR_CMND_NOOP }, /* EVT:  CMND_NOOP */
    { SMTP_SERVER_ST_HELLO, SMTP_SERVER_TR_CMND_HELO }, /* EVT:  CMND_HELO */
    { SMTP_SERVER_ST_HELLO, SMTP_SERVER_TR_CMND_EHLO }, /* EVT:  CMND_EHLO */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_MAIL */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_RCPT */
    { SMTP_SERVER_ST_READY, SMTP_SERVER_TR_CMND_VRFY }, /* EVT:  CMND_VRFY */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_DATA */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_RSET */
    { SMTP_SERVER_ST_CLOSED, SMTP_SERVER_TR_CMND_CLOSE }, /* EVT:  CMND_QUIT */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  MAIL_END */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  MAIL_DATA */
    { SMTP_SERVER_ST_READY, SMTP_SERVER_TR_ACCEPTED }, /* EVT:  CONN_ACCEPTED */
    { SMTP_SERVER_ST_CLOSED, SMTP_SERVER_TR_CMND_CLOSE } /* EVT:  CONN_LOST */
  },


  /* STATE 2:  SMTP_SERVER_ST_HELLO */
  { { SMTP_SERVER_ST_HELLO, SMTP_SERVER_TR_CMND_NOOP }, /* EVT:  CMND_NOOP */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_HELO */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_EHLO */
    { SMTP_SERVER_ST_MAIL, SMTP_SERVER_TR_CMND_MAIL }, /* EVT:  CMND_MAIL */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_RCPT */
    { SMTP_SERVER_ST_HELLO, SMTP_SERVER_TR_CMND_VRFY }, /* EVT:  CMND_VRFY */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_DATA */
    { SMTP_SERVER_ST_HELLO, SMTP_SERVER_TR_CMND_RSET }, /* EVT:  CMND_RSET */
    { SMTP_SERVER_ST_CLOSED, SMTP_SERVER_TR_CMND_CLOSE }, /* EVT:  CMND_QUIT */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  MAIL_END */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  MAIL_DATA */
    { SMTP_SERVER_ST_READY, SMTP_SERVER_TR_ACCEPTED }, /* EVT:  CONN_ACCEPTED */
    { SMTP_SERVER_ST_CLOSED, SMTP_SERVER_TR_CMND_CLOSE } /* EVT:  CONN_LOST */
  },


  /* STATE 3:  SMTP_SERVER_ST_MAIL */
  { { SMTP_SERVER_ST_MAIL, SMTP_SERVER_TR_CMND_NOOP }, /* EVT:  CMND_NOOP */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_HELO */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_EHLO */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_MAIL */
    { SMTP_SERVER_ST_RCPT, SMTP_SERVER_TR_CMND_RCPT }, /* EVT:  CMND_RCPT */
    { SMTP_SERVER_ST_MAIL, SMTP_SERVER_TR_CMND_VRFY }, /* EVT:  CMND_VRFY */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_DATA */
    { SMTP_SERVER_ST_HELLO, SMTP_SERVER_TR_CMND_RSET }, /* EVT:  CMND_RSET */
    { SMTP_SERVER_ST_CLOSED, SMTP_SERVER_TR_CMND_CLOSE }, /* EVT:  CMND_QUIT */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  MAIL_END */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  MAIL_DATA */
    { SMTP_SERVER_ST_READY, SMTP_SERVER_TR_ACCEPTED }, /* EVT:  CONN_ACCEPTED */
    { SMTP_SERVER_ST_CLOSED, SMTP_SERVER_TR_CMND_CLOSE } /* EVT:  CONN_LOST */
  },


  /* STATE 4:  SMTP_SERVER_ST_RCPT */
  { { SMTP_SERVER_ST_RCPT, SMTP_SERVER_TR_CMND_NOOP }, /* EVT:  CMND_NOOP */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_HELO */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_EHLO */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_MAIL */
    { SMTP_SERVER_ST_RCPT, SMTP_SERVER_TR_CMND_RCPT }, /* EVT:  CMND_RCPT */
    { SMTP_SERVER_ST_RCPT, SMTP_SERVER_TR_CMND_VRFY }, /* EVT:  CMND_VRFY */
    { SMTP_SERVER_ST_DATA, SMTP_SERVER_TR_CMND_DATA }, /* EVT:  CMND_DATA */
    { SMTP_SERVER_ST_HELLO, SMTP_SERVER_TR_CMND_RSET }, /* EVT:  CMND_RSET */
    { SMTP_SERVER_ST_CLOSED, SMTP_SERVER_TR_CMND_CLOSE }, /* EVT:  CMND_QUIT */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  MAIL_END */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  MAIL_DATA */
    { SMTP_SERVER_ST_READY, SMTP_SERVER_TR_ACCEPTED }, /* EVT:  CONN_ACCEPTED */
    { SMTP_SERVER_ST_CLOSED, SMTP_SERVER_TR_CMND_CLOSE } /* EVT:  CONN_LOST */
  },


  /* STATE 5:  SMTP_SERVER_ST_DATA */
  { { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_NOOP */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_HELO */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_EHLO */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_MAIL */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_RCPT */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_VRFY */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_DATA */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_RSET */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_QUIT */
    { SMTP_SERVER_ST_HELLO, SMTP_SERVER_TR_MAIL_END }, /* EVT:  MAIL_END */
    { SMTP_SERVER_ST_DATA, SMTP_SERVER_TR_MAIL_DATA }, /* EVT:  MAIL_DATA */
    { SMTP_SERVER_ST_READY, SMTP_SERVER_TR_ACCEPTED }, /* EVT:  CONN_ACCEPTED */
    { SMTP_SERVER_ST_CLOSED, SMTP_SERVER_TR_CMND_CLOSE } /* EVT:  CONN_LOST */
  },


  /* STATE 6:  SMTP_SERVER_ST_CLOSED */
  { { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_NOOP */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_HELO */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_EHLO */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_MAIL */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_RCPT */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_VRFY */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_DATA */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_RSET */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  CMND_QUIT */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  MAIL_END */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID }, /* EVT:  MAIL_DATA */
    { SMTP_SERVER_ST_READY, SMTP_SERVER_TR_ACCEPTED }, /* EVT:  CONN_ACCEPTED */
    { SMTP_SERVER_ST_INVALID, SMTP_SERVER_TR_INVALID } /* EVT:  CONN_LOST */
  }
};


#define Smtp_ServerFsmErr_off     19
#define Smtp_ServerEvInvalid_off  75
#define Smtp_ServerStInit_off     83


static char const zSmtp_ServerStrings[255] =
/*     0 */ "** OUT-OF-RANGE **\0"
/*    19 */ "FSM Error:  in state %d (%s), event %d (%s) is invalid\n\0"
/*    75 */ "invalid\0"
/*    83 */ "init\0"
/*    88 */ "ready\0"
/*    94 */ "hello\0"
/*   100 */ "mail\0"
/*   105 */ "rcpt\0"
/*   110 */ "data\0"
/*   115 */ "closed\0"
/*   122 */ "cmnd_noop\0"
/*   132 */ "cmnd_helo\0"
/*   142 */ "cmnd_ehlo\0"
/*   152 */ "cmnd_mail\0"
/*   162 */ "cmnd_rcpt\0"
/*   172 */ "cmnd_vrfy\0"
/*   182 */ "cmnd_data\0"
/*   192 */ "cmnd_rset\0"
/*   202 */ "cmnd_quit\0"
/*   212 */ "mail_end\0"
/*   221 */ "mail_data\0"
/*   231 */ "conn_accepted\0"
/*   245 */ "conn_lost";

static const size_t aszSmtp_ServerStates[7] = {
    83,  88,  94,  100, 105, 110, 115 };

static const size_t aszSmtp_ServerEvents[14] = {
    122, 132, 142, 152, 162, 172, 182, 192, 202, 212, 221, 231, 245, 75 };


#define SMTP_SERVER_EVT_NAME(t)   ( (((unsigned)(t)) >= 14) \
    ? zSmtp_ServerStrings : zSmtp_ServerStrings + aszSmtp_ServerEvents[t])

#define SMTP_SERVER_STATE_NAME(s) ( (((unsigned)(s)) >= 7) \
    ? zSmtp_ServerStrings : zSmtp_ServerStrings + aszSmtp_ServerStates[s])

#ifndef EXIT_FAILURE
# define EXIT_FAILURE 1
#endif

static int smtp_server_invalid_transition( te_smtp_server_state st, te_smtp_server_event evt );

/* * * * * * * * * THE CODE STARTS HERE * * * * * * * */
/**
 *  Print out an invalid transition message and return EXIT_FAILURE
 */
static int
smtp_server_invalid_transition( te_smtp_server_state st, te_smtp_server_event evt )
{
    /* START == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */
    char const * fmt = zSmtp_ServerStrings + Smtp_ServerFsmErr_off;
    fprintf( stderr, fmt, st, SMTP_SERVER_STATE_NAME(st), evt, SMTP_SERVER_EVT_NAME(evt));
    /* END   == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */

    return EXIT_FAILURE;
}

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  SMTP_SERVER_ST_DONE or SMTP_SERVER_ST_INVALID, it resets to
 *  SMTP_SERVER_ST_INIT and returns SMTP_SERVER_ST_INIT.
 */
te_smtp_server_state
smtp_server_step(
    te_smtp_server_state smtp_server_state,
    te_smtp_server_event trans_evt,
    void* client,
    const char* matchdata )
{
    te_smtp_server_state nxtSt;
    te_smtp_server_trans trans;

    if ((unsigned)smtp_server_state >= SMTP_SERVER_ST_INVALID) {
        return SMTP_SERVER_ST_INIT;
    }

#ifndef __COVERITY__
    if (trans_evt >= SMTP_SERVER_EV_INVALID) {
        nxtSt = SMTP_SERVER_ST_INVALID;
        trans = SMTP_SERVER_TR_INVALID;
    } else
#endif /* __COVERITY__ */
    {
        const t_smtp_server_transition * ttbl =
            smtp_server_trans_table[ smtp_server_state ] + trans_evt;
        nxtSt = ttbl->next_state;
        trans = ttbl->transition;
    }


    switch (trans) {
    case SMTP_SERVER_TR_ACCEPTED:
        /* START == ACCEPTED == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_ACCEPTED(client, nxtSt);
        /* END   == ACCEPTED == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_TR_CMND_CLOSE:
        /* START == CMND_CLOSE == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_CMND_CLOSE(client, nxtSt);
        /* END   == CMND_CLOSE == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_TR_CMND_DATA:
        /* START == CMND_DATA == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_CMND_DATA(client, nxtSt);
        /* END   == CMND_DATA == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_TR_CMND_EHLO:
        /* START == CMND_EHLO == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_CMND_EHLO(client, matchdata, nxtSt);
        /* END   == CMND_EHLO == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_TR_CMND_HELO:
        /* START == CMND_HELO == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_CMND_HELO(client, matchdata, nxtSt);
        /* END   == CMND_HELO == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_TR_CMND_MAIL:
        /* START == CMND_MAIL == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_CMND_MAIL(client, matchdata, nxtSt);
        /* END   == CMND_MAIL == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_TR_CMND_NOOP:
        /* START == CMND_NOOP == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_CMND_NOOP(client, nxtSt);
        /* END   == CMND_NOOP == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_TR_CMND_RCPT:
        /* START == CMND_RCPT == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_CMND_RCPT(client, matchdata, nxtSt);
        /* END   == CMND_RCPT == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_TR_CMND_RSET:
        /* START == CMND_RSET == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_CMND_RSET(client, nxtSt);
        /* END   == CMND_RSET == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_TR_CMND_VRFY:
        /* START == CMND_VRFY == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_CMND_VRFY(client, nxtSt);
        /* END   == CMND_VRFY == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_TR_INVALID:
        /* START == INVALID == DO NOT CHANGE THIS COMMENT */
        printf( "Transition is invalid" );
        nxtSt = HANDLE_ERROR(client, nxtSt);
        // exit(smtp_server_invalid_transition(smtp_server_state, trans_evt));
        /* END   == INVALID == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_TR_MAIL_DATA:
        /* START == MAIL_DATA == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_MAIL_DATA(client, matchdata, nxtSt);
        /* END   == MAIL_DATA == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_TR_MAIL_END:
        /* START == MAIL_END == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_MAIL_END(client, nxtSt);
        /* END   == MAIL_END == DO NOT CHANGE THIS COMMENT */
        break;


    default:
        /* START == BROKEN MACHINE == DO NOT CHANGE THIS COMMENT */
        exit(smtp_server_invalid_transition(smtp_server_state, trans_evt));
        /* END   == BROKEN MACHINE == DO NOT CHANGE THIS COMMENT */
    }


    /* START == FINISH STEP == DO NOT CHANGE THIS COMMENT */
    /* END   == FINISH STEP == DO NOT CHANGE THIS COMMENT */

    return nxtSt;
}
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of server-fsm.c */
